musicbrainz.url=https://musicbrainz.org
micronaut.http.services.setlist-fm.url=https://api.setlist.fm
setlist-fm.api-key=dummy-setlist-fm-api-key
# Always write recentSetlists (even when empty) and null fields.
micronaut.serde.serialization.inclusion=always
